In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress
import scipy.stats as st

In [13]:
#top&bottom csvs
T_pop = pd.read_csv("mostchangedpop.csv")
B_pop = pd.read_csv("leastchangedpop.csv")


#data set with changing rates
population_df = pd.read_csv("sorted_population_final.csv")
rental_df = pd.read_csv("rental_rate.csv")
housing_df = pd.read_csv("housing_rate.csv")

In [21]:
#finding common cities in all three data set
pop = population_df[["City", "State"]]
ren = rental_df[["City", "State"]]
hou = housing_df[["City", "State"]]

commons = ren.merge(pop, on="City", how="left")
common= commons.merge(hou, on="City", how="left")
common = common["City"].unique()

In [15]:
newList = []
for index,row in population_df.iterrows():
    for city in common:
        if city in row["City"]:
            newList.append({
                "city":row["City"],
                "PDR1819": row["2018-2019 Population Rate"],
                "PDR1920": row["2019-2020 Population Rate"],
                
            })
newHousing=[ ] 
for index,row in housing_df.iterrows():
    for city in common:
        if city in row["City"]:
            newHousing.append({
                "city":row["City"],
                "HDR1819": row["2018-2019 changing rate"],
                "HDR1920": row["2019-2020 changing rate"]
                
            })

newRental = [ ] 
for index,row in rental_df.iterrows():
    for city in common:
        if city in row["City"]:
            newRental.append({
                "city":row["City"],
                "RDR1819": row["2018-2019 changing rate"],
                "RDR1920": row["2019-2020 changing rate"]
                               })

In [16]:
newList = pd.DataFrame(newList)
newHousing = pd.DataFrame(newHousing)
newRental = pd.DataFrame(newRental)

In [22]:
newList["HDR1819"]=newHousing["HDR1819"]
newList["HDR1920"]=newHousing["HDR1920"]
newList["RDR1819"]=newRental["RDR1819"]
newList["RDR1920"]=newRental["RDR1920"]
newList.to_csv("CsvFiles/ChangingRates.csv")
newList

,city,PDR1819,PDR1920,HDR1819,HDR1920,RDR1819,RDR1920
0,Salt Lake City,0.065857,6.381907,2.319249,3.357083,2.314455,-0.639372
1,Miami,1.111450,3.937277,1.759587,4.643373,3.534751,1.173697
2,Seattle,1.541291,3.909112,2.225370,5.527680,2.377688,0.673756
3,Tampa,0.621299,3.503628,2.406569,4.862630,3.263806,1.545500
4,Atlanta,1.731894,3.339904,4.091464,4.960132,3.209798,1.773491
...,...,...,...,...,...,...,...
76,Omaha,0.187094,-1.566316,4.566399,6.480742,5.276257,4.463610
77,Baton Rouge,-0.879428,-1.605096,3.002443,4.881788,2.645242,1.842762
78,Pittsburgh,-0.094487,-1.806944,5.301395,5.614423,2.975016,5.000586
79,St. Louis,-0.936988,-2.257000,4.850413,8.870747,4.970421,4.126580
80,Columbus,0.824024,-3.306448,5.489783,6.828545,4.607823,3.326074